// Icons
export default {
    home: require("./icons/png/home/home.png"),
    homeActive: require("./icons/png/home-active/home-active.png"),
    library: require("./icons/png/library/library.png"),
    libraryActive: require("./icons/png/library-active/library-active.png"),
    you: require("./icons/png/you/you.png"),
    youActive: require("./icons/png/you-active/you-active.png"),
    notebook: require("./icons/png/notebook/notebook.png"),
    notebookActive: require("./icons/png/notebook-active/notebook-active.png"),
    gears: require("./icons/png/gears/gears.png"),
    headGears: require("./icons/png/head-gears/head-gears.png"),
    play: require("./icons/png/play/play.png"),
    completed: require("./icons/png/completed/completed.png"),
    lock: require("./icons/png/lock/lock.png"),
    medal: require("./icons/png/medal/medal.png"),
    time: require("./icons/png/time/time.png"),
    cog: require("./icons/png/cog/cog.png"),
    audio: require("./icons/png/audio/audio.png"),
    chevronRightPurple: require("./icons/png/chevron-right-purple/chevron-right-purple.png"),
    chevronPurple: require("./icons/png/chevron-purple/chevron-purple.png"),
    chevronDownPurple: require("./icons/png/chevron-down-purple/chevron-down-purple.png"),
    arrowDownYellow: require("./icons/png/arrow-down-yellow/arrow-down-yellow.png"),
    arrowDownGreen: require("./icons/png/arrow-down-green/arrow-down-green.png"),
    arrowDownRed: require("./icons/png/arrow-down-red/arrow-down-red.png"),
    send: require("./icons/png/send/send.png"),
    logoHead: require("./icons/png/logo-head/logo-head.png"),
    chevronUpBlue: require("./icons/png/chevron-up-blue/chevron-up-blue.png"),
    language: require("./icons/png/language/language@3x.png"),
    location: require("./icons/png/location/location@3x.png"),
    education: require("./icons/png/education/education@3x.png"),
    telephone: require("./icons/png/telephone/telephone@3x.png"),
    success: require("./icons/png/success/success@3x.png"),
    close: require("./icons/png/close/close@3x.png"),
    password: {
        src: "",
        height: "1rem",
        width: "1rem"
    },
    information: {
        src: "",
        height: "1rem",
        width: "0.4375rem"
    }
}
